version: "3.1"

services:
  app:
    build: ./src
    tty: true
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - CH_ID=${CH_ID}
    volumes:
      - ./src:/root/src
