version: "3.1"

services:
  app:
    image: ghcr.io/102ch/tokumei-bot:latest
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - CH_ID=${CH_ID}
    volumes:
      - ./src:/root/src
